###
GET http://localhost:3000

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users?role=ADMIN&page=1&limit=1

###
GET http://localhost:3000/users/20

###
POST http://localhost:3000/users
Content-Type: application/json

{
"name": "Clementine",
"email": "Clementine@mail.com",
"role": "ADMIN",
"dateOfBirth": "2000-02-19"
}

###
PATCH  http://localhost:3000/users/4
Content-Type: application/json

{
"name": "Clementine",
"email": "Clementine@mail.com"
}

###
DELETE  http://localhost:3000/users/4

### Create group
POST http://localhost:3000/grouplists
Content-Type: application/json

{
"name": "My Favourites",
"ownerId": 20
}