###
GET http://localhost:3000

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users?role=ADMIN&page=1&limit=1

###
GET http://localhost:3000/users/20

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"name": "Gara the sand",
"email": "gara.sand@mail.com",
"role": "ENGINEER",
"dateOfBirth": "2003-01-09",
"password": "123456"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "email": "Clementine@mail.com",
    "password": "123456"
}

###
PATCH  http://localhost:3000/users/4
Content-Type: application/json

{
"name": "Clementine",
"email": "Clementine@mail.com"
}

###
DELETE  http://localhost:3000/users/4

### Create group
POST http://localhost:3000/grouplists
Content-Type: application/json

{
"name": "My Favourites",
"ownerId": 20
}