###
GET http://localhost:3000

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users?role=ENGINEER

###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/users
Content-Type: application/json

{
"name": "Gara the sand",
"email": "gara.sand@mail.com",
"role": "INTERN"
}

###
PATCH  http://localhost:3000/users/3
Content-Type: application/json

{
"email": "Clementine@mail.com"
}

###
DELETE  http://localhost:3000/users/4